name: Domosense UI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn -v
      - run: yarn install
      - run: yarn prod
      # - run: yarn test
      #   env:
      #     CI: true
      # - uses: actions/upload-artifact@v1
      #   with:
      #     name: domosense-ui
      #     path: build
