name: Tests

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn -v
      - run: yarn install
      - run: yarn test
        env:
          CI: true
